name: Qukkiz
main: nl.blaatz0r.Trivia.Trivia
description: Qukkiz is a quiz game that is played in the minecraft chatbox.
version: 0.5.1
authors:
    - 'xZise'
    - 'blaatz0r'
commands:    
    qukkiz:
        description: Handle Qukkiz.
        usage: /<command> help - Show the help of qukkiz-commands.
        aliases: [trivia]