name: Trivia
main: nl.blaatz0r.Trivia.Trivia
description: Qukkiz is a quiz game that is played in the minecraft chatbox.
version: 1.6
authors:
    - 'xZise'
    - 'blaatz0r'
commands:
    next:
        description: Skips to the next Trivia question
        usage: /<command>
        
    votenext:
        description: Calls a vote for the next Trivia question
        usage: /<command>
        
    hint:
        description: Calls the next hint for the current Trivia question, if possible
        usage: /<command>
    
    qukkiz:
        description: Handle Qukkiz.
        usage: /<command> help - Show the help of qukkiz-commands.
        aliases: [trivia]